version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabotchanges"
    commit-message:
      prefix: "build"
    open-pull-requests-limit: 10
    groups:
      github-actions-security:
        applies-to: "security-updates"
      github-actions-version:
        applies-to: "version-updates"

  # Python backend dependencies
  - package-ecosystem: "pip"
    directory: "/src/api"
    schedule:
      interval: "monthly"
    target-branch: "dependabotchanges"
    commit-message:
      prefix: "build"
    open-pull-requests-limit: 10
    groups:
      backend-security:
        applies-to: "security-updates"
      backend-version:
        applies-to: "version-updates"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/App"
    schedule:
      interval: "monthly"
    target-branch: "dependabotchanges"
    commit-message:
      prefix: "build"
    open-pull-requests-limit: 10
    registries:
      - npm_public_registry
    groups:
      frontend-security:
        applies-to: "security-updates"
      frontend-version:
        applies-to: "version-updates"

registries:
  npm_public_registry:
    type: "npm-registry"
    url: "https://registry.npmjs.org/"
    token: "${{ secrets.TOKEN }}"
